"""Added additional fields to Ticket, User. Added Ticket_Notes table.

Revision ID: 7bd37df63c3e
Revises: 28b1ef26352e
Create Date: 2020-03-09 20:56:19.992428

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7bd37df63c3e'
down_revision = '28b1ef26352e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ticket__notes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('added_datetime', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('ticket_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['ticket_id'], ['ticket.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('ticket', sa.Column('closed_datetime', sa.DateTime(), nullable=True))
    op.add_column('ticket', sa.Column('created_by', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'ticket', 'user', ['created_by'], ['id'])
    op.add_column('user', sa.Column('first_name', sa.String(length=40), nullable=True))
    op.add_column('user', sa.Column('last_name', sa.String(length=60), nullable=True))
    op.add_column('user', sa.Column('registration_date', sa.DateTime(), nullable=False, server_default=sa.func.current_timestamp()))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'registration_date')
    op.drop_column('user', 'last_name')
    op.drop_column('user', 'first_name')
    op.drop_constraint(None, 'ticket', type_='foreignkey')
    op.drop_column('ticket', 'created_by')
    op.drop_column('ticket', 'closed_datetime')
    op.drop_table('ticket__notes')
    # ### end Alembic commands ###
